import Head from "next/head";
import { API } from "@stoplight/elements";
import "@stoplight/elements/styles.min.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Vercel Rest API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <API
        apiDescriptionUrl="https://openapi.vercel.sh/"
        router={typeof window === "undefined" ? "memory" : "history"}
      />
    </div>
  );
}
